import type { Job } from "@/types";

/** משרות מותאמות לאנשים על הרצף האוטיסטי — סביבות מובנות, אינטראקיה נמוכה, ליווי */
export const mockJobs: Job[] = [
  {
    id: "job-001",
    title: "בודק/ת תוכנה (QA)",
    company: "מיקרוסופט ישראל (מ.development)",
    city: "הרצליה · היברידי",
    description:
      "בדיקת מערכות web ו-mobile. צוות קטן, משימות מוגדרות, לוח זמנים ברור. ליווי מקצועי מסוכנות שילובים.",
    salary: "10,000 - 14,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=QA",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-15T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["ליווי בתעסוקה", "משימות כתובות", "סביבה שקטה"],
    autism_match_reason: "עבודה מובנית עם צ'ק-ליסטים — מתאימה לחשיבה מדויקת ולריכוז.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-001",
  },
  {
    id: "job-002",
    title: "מעצב/ת גרפי",
    company: "סטודיו Pixel א'",
    city: "חיפה · מהבית",
    description:
      "עיצוב חומרי שיווק בפרויקטים בודדים. תקשורת בעיקר במייל ו-Slack, ללא פגישות לקוחות ישירות.",
    salary: "9,000 - 13,000 ₪",
    apply_url: "https://www.drushim.co.il/jobs/subcat/24/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה חלקית",
    active: true,
    created_at: "2026-06-14T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["עבודה מהבית", "משימות כתובות", "גמישות בשעות"],
    autism_match_reason: "יצירתיות + עבודה עצמאית — מינימום אינטראקיה חברתית.",
    disability_fit: ["ADHD", "חרדה חברתית", "אוטיזם"],
    profession_id: "prof-002",
  },
  {
    id: "job-003",
    title: "הנהלת חשבונות",
    company: "משרד רואי חשבון לוי ושות'",
    city: "ירושלים",
    description:
      "הזנת נתונים, התאמות ודוחות. משרד נגיש, חדר עבודה שקט, הוראות מפורטות לכל משימה.",
    salary: "11,000 - 15,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=הנהלת%20חשבונות",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-13T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["משרד נגיש", "סביבה שקטה", "משימות כתובות"],
    autism_match_reason: "דיוק, סדר ושגרה קבועה — חוזקות נפוצות בקרב אנשים על הרצף.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-003",
  },
  {
    id: "job-004",
    title: "מפתח/ת Frontend",
    company: "Wix · תוכנית שילוב",
    city: "תל אביב · היברידי",
    description:
      "פיתוח ממשקי React. מנטור ייעודי, stand-up קצר, עבודה בזוגות אופציונלית בלבד.",
    salary: "16,000 - 24,000 ₪",
    apply_url: "https://www.shiluvim.org.il/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-12T08:00:00Z",
    social_interaction_level: "בינוני",
    support_features: ["ליווי בתעסוקה", "מנטור ייעודי", "עבודה מהבית חלקית"],
    autism_match_reason: "חשיבה לוגית ופתרון בעיות — עם ליווי מסודר מהיום הראשון.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-004",
  },
  {
    id: "job-005",
    title: "הזנת נתונים",
    company: "חברת ביטוח לאומי — מוקד מידע",
    city: "באר שבע",
    description:
      "הזנת מידע למערכות CRM לפי טופס קבוע. משמרות קבועות, הפסקות מובנות, ללא שיחות טלפון.",
    salary: "7,500 - 9,500 ₪",
    apply_url: "https://www.taasuka.gov.il/",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-11T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["משימות כתובות", "שגרה קבועה", "סביבה שקטה"],
    autism_match_reason: "משימות חוזרות וברורות — מינימום הפתעות ושינויים.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-010",
  },
  {
    id: "job-006",
    title: "עורך/ת וידאו",
    company: "עמותת תקשורת חברתית",
    city: "תל אביב · מהבית",
    description:
      "עריכת סרטוני הסברה. עבודה עצמאית, דד-ליינים ברורים, מפגש צוות שבועי אחד בלבד.",
    salary: "9,500 - 14,000 ₪",
    apply_url: "https://www.drushim.co.il/jobs/subcat/45/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה חלקית",
    active: true,
    created_at: "2026-06-10T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["עבודה מהבית", "גמישות בשעות", "משימות כתובות"],
    autism_match_reason: "עבודה יצירתית בקצב אישי, עם מעט אינטראקיה חברתית.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-007",
  },
  {
    id: "job-007",
    title: "ארכיונאי/ת דיגיטלי",
    company: "ארכיון המדינה",
    city: "ירושלים",
    description:
      "סריקה, סיווג ושמירה של מסמכים. סביבת עבודה שקטה, משימות מוגדרות, משרד מונגש.",
    salary: "8,000 - 10,500 ₪",
    apply_url: "https://www.gov.il/he/Departments/publications",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-09T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["משרד נגיש", "סביבה שקטה", "שגרה קבועה"],
    autism_match_reason: "סדר, דיוק וארגון — עבודה שיטתית ללא לחץ חברתי.",
    disability_fit: ["חרדה חברתית", "אוטיזם", "לקות ראייה"],
    profession_id: "prof-012",
  },
  {
    id: "job-008",
    title: "כותב/ת תוכן טכני",
    company: "חברת SaaS ישראלית",
    city: "רמת גן · מהבית",
    description:
      "כתיבת מדריכי שימוש למוצרי תוכנה. עבודה עם מפתחים בכתב בלבד, ללא מצגות.",
    salary: "10,000 - 15,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=כותב%20תוכן",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-08T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["עבודה מהבית", "משימות כתובות", "גמישות בשעות"],
    autism_match_reason: "כתיבה מדויקת ומובנית — מתאימה לחשיבה analitית.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-014",
  },
  {
    id: "job-009",
    title: "מעצב/ת UX",
    company: "Bank Leumi Digital",
    city: "תל אביב · היברידי",
    description:
      "תכנון ממשקים נגישים. צוות inclusive, ליווי HR, אפשרות לעבודה מהבית 3 ימים.",
    salary: "15,000 - 22,000 ₪",
    apply_url: "https://www.drushim.co.il/jobs/subcat/24/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-07T08:00:00Z",
    social_interaction_level: "בינוני",
    support_features: ["ליווי בתעסוקה", "עבודה מהבית חלקית", "משרד נגיש"],
    autism_match_reason: "חשיבה ויזualית ו-systematic — עם תמיכה ארגונית מלאה.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-013",
  },
  {
    id: "job-010",
    title: "ניתוח נתונים (Junior)",
    company: "חברת ביטוח — יחידת BI",
    city: "פתח תקווה",
    description:
      "עבודה עם Excel ו-SQL על דוחות קבועים. הדרכה מובנית, חדר שקט זמין, ליווי שילובים.",
    salary: "12,000 - 16,000 ₪",
    apply_url: "https://www.shiluvim.org.il/",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-06T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["ליווי בתעסוקה", "הדרכה מובנית", "סביבה שקטה"],
    autism_match_reason: "עבודה עם מספרים ודפוסים — חוזקה משמעותית בקרב אוטיסטים.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-016",
  },
  {
    id: "job-011",
    title: "תמיכה טכנית (צ'at)",
    company: "Monday.com",
    city: "תל אביב · מהבית",
    description:
      "מענה ללקוחות בצ'at בלבד — ללא שיחות טלפון. תסריטי תשובות מוכנים, משמרות קבועות.",
    salary: "9,000 - 12,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=תמיכה%20טכנית",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-05T08:00:00Z",
    social_interaction_level: "בינוני",
    support_features: ["עבודה מהבית", "תסריטים מוכנים", "משמרות קבועות"],
    autism_match_reason: "תקשורת בכתב עם תבניות — פחות עומס חברתי מאשר טלפון.",
    disability_fit: ["ADHD", "חרדה חברתית", "אוטיזם"],
    profession_id: "prof-005",
  },
  {
    id: "job-012",
    title: "ספרן/ית — מדור דיגיטל",
    company: "ספריית העיר תל אביב",
    city: "תל אביב",
    description:
      "סיוע בקטalog דיגיטלי, סביבה שקטה, אינטראקיה עם קהל מינימלית ומובנית.",
    salary: "8,000 - 10,000 ₪",
    apply_url: "https://www.taasuka.gov.il/",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-04T08:00:00Z",
    social_interaction_level: "בינוני",
    support_features: ["משרד נגיש", "סביבה שקטה", "שגרה קבועה"],
    autism_match_reason: "סביבה רגועה, משימות מובנות, אינטראקיה קצרה וצפויה.",
    disability_fit: ["חרדה חברתית", "אוטיזם", "לקות ראייה"],
    profession_id: "prof-009",
  },
  {
    id: "job-013",
    title: "אבטחת מידע — Junior Analyst",
    company: "חברת סייבר Check Point",
    city: "תל אביב · היברידי",
    description:
      "ניטור אירועי אבטחה לפי נוהל. משמרות מוגדרות, הכשרה מלאה, מנטור מסוכנות שילובים.",
    salary: "14,000 - 20,000 ₪",
    apply_url: "https://www.drushim.co.il/jobs/subcat/1/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-03T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["ליווי בתעסוקה", "הדרכה מובנית", "עבודה מהבית חלקית"],
    autism_match_reason: "חשיבה לוגית, תשומת לב לפרטים, עבודה לפי פרוטוקול.",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    profession_id: "prof-018",
  },
  {
    id: "job-014",
    title: "איור דיגיטלי",
    company: "סטודיו משחקים indie",
    city: "חיפה · מהבית",
    description:
      "יצירת דמויות ורקעים למשחק מובייל. תקשורת בDiscord, דד-ליינים שבועיים.",
    salary: "8,000 - 13,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=איור",
    work_from_home: true,
    accessibility: true,
    scope: "פרילנס",
    active: true,
    created_at: "2026-06-02T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["עבודה מהבית", "גמישות בשעות", "משימות כתובות"],
    autism_match_reason: "יצירתיות ויזualית + עבודה עצמאית — מינימום לחץ חברתי.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-019",
  },
  {
    id: "job-015",
    title: "בקר/ת איכות — מפעל אלקטרוניקה",
    company: "אינטל קריית גת",
    city: "קרית גת",
    description:
      "בדיקת רכיבים לפי מפרט. סביבה מובנית, משמרות קבועות, ליווי עמותת AKIM.",
    salary: "9,000 - 12,000 ₪",
    apply_url: "https://www.akim.org.il/",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-06-01T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["ליווי בתעסוקה", "שגרה קבועה", "משימות כתובות"],
    autism_match_reason: "דיוק, חזרתיות ומבנה — מתאים במיוחד לאוטיזם.",
    disability_fit: ["אוטיזם", "ADHD", "לקות פיזית"],
    profession_id: "prof-027",
  },
  {
    id: "job-016",
    title: "שרטוט CAD — Junior",
    company: "משרד אדריכלות Cohen",
    city: "חולון",
    description:
      "הכנת שרטוטים טכניים לפי הנחיות. עבודה בודדת, הוראות מפורטות, משרד שקט.",
    salary: "10,000 - 14,000 ₪",
    apply_url: "https://www.alljobs.co.il/SearchResultsGuest.aspx?position=שרטוט",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-05-30T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["סביבה שקטה", "משימות כתובות", "שגרה קבועה"],
    autism_match_reason: "דיוק מרחבי, עבודה טכנית — חוזקות cognitivיות נפוצות.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-024",
  },
  {
    id: "job-017",
    title: "נגרות — סדנה מוגנת",
    company: "סדנת מקור — שילובים",
    city: "ראשון לציון",
    description:
      "ייצור רהיטים לפי תוכנית. סדנה מוגנת, ליווי מלא, קצב אישי מותאם.",
    salary: "8,000 - 11,000 ₪",
    apply_url: "https://www.shiluvim.org.il/",
    work_from_home: false,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-05-28T08:00:00Z",
    social_interaction_level: "נמוך",
    support_features: ["ליווי בתעסוקה", "קצב אישי", "סביבה שקטה"],
    autism_match_reason: "עבודת ידיים מובנית, תוצר מוחשי, סביבה תומכת.",
    disability_fit: ["ADHD", "לקות למידה", "לקות פיזית"],
    profession_id: "prof-015",
  },
  {
    id: "job-018",
    title: "מפתח/ת אפליקציות מובייל",
    company: "סטארטאפ HealthTech",
    city: "רמת גן · היברידי",
    description:
      "פיתוח Flutter. צוות neurodiverse-friendly, quiet room, async communication.",
    salary: "17,000 - 26,000 ₪",
    apply_url: "https://www.drushim.co.il/jobs/subcat/1/",
    work_from_home: true,
    accessibility: true,
    scope: "משרה מלאה",
    active: true,
    created_at: "2026-05-26T08:00:00Z",
    social_interaction_level: "בינוני",
    support_features: ["ליווי בתעסוקה", "עבודה מהבית חלקית", "סביבה שקטה"],
    autism_match_reason: "חשיבה לוגית + סביבת עבודה inclusive מודעת לאוטיזם.",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    profession_id: "prof-025",
  },
];
