import type { Profession } from "@/types";
import { PROFESSION_CATEGORY_BY_ID } from "./profession-categories";

export const mockProfessions: Profession[] = [
  {
    id: "prof-001",
    name: "בדיקות תוכנה (QA)",
    description: "בדיקת תוכנות ומערכות לאיתור תקלות לפני שחרור למשתמשים",
    salary_range: "8,000 - 18,000 ₪",
    education: "קורס QA (3-6 חודשים)",
    skills: ["ריכוז", "סדר", "חשיבה לוגית", "דיווח"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-002",
    name: "עיצוב גרפי",
    description: "יצירת עיצובים ויזואליים לדיגיטל ודפוס",
    salary_range: "7,000 - 16,000 ₪",
    education: "קורס עיצוב גרפי / תעודה",
    skills: ["יצירתיות", "תשומת לב לפרטים", "תוכנות עיצוב"],
    work_environment: "משרד / מהבית / פרילנס",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "חרדה חברתית", "לקות ראייה חלקית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-003",
    name: "הנהלת חשבונות",
    description: "ניהול חשבונות, חשבוניות ודוחות כספיים לעסקים",
    salary_range: "9,000 - 20,000 ₪",
    education: "קורס הנהלת חשבונות + הסמכה",
    skills: ["סדר", "דיוק", "מספרים", "ארגון"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-004",
    name: "פיתוח תוכנה",
    description: "כתיבת קוד ובניית אפליקציות ואתרים",
    salary_range: "15,000 - 35,000 ₪",
    education: "קורס פיתוח / תואר רלוונטי",
    skills: ["חשיבה לוגית", "פתרון בעיות", "למידה עצמאית"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-005",
    name: "תמיכה טכנית",
    description: "מתן תמיכה טכנית למשתמשים במוצרים דיגיטליים",
    salary_range: "8,000 - 14,000 ₪",
    education: "קורס מחשבים / הכשרה מקצועית",
    skills: ["סבלנות", "תקשורת", "פתרון בעיות"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "לקות שמיעה", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-006",
    name: "צילום",
    description: "צילום אירועים, מוצרים ותוכן שיווקי",
    salary_range: "6,000 - 15,000 ₪",
    education: "קורס צילום / לימוד עצמי",
    skills: ["יצירתיות", "תשומת לב", "עבודה עצמאית"],
    work_environment: "שטח / סטודיו / פרילנס",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "חרדה חברתית", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-007",
    name: "עריכת וידאו",
    description: "עריכת סרטונים לשיווק, רשתות חברתיות ותוכן",
    salary_range: "8,000 - 18,000 ₪",
    education: "קורס עריכה / הכשרה מקצועית",
    skills: ["יצירתיות", "סבלנות", "תוכנות עריכה"],
    work_environment: "מהבית / משרד",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-008",
    name: "ניהול משרד",
    description: "ניהול משרד, תיאום פגישות וארגון מסמכים",
    salary_range: "7,000 - 12,000 ₪",
    education: "קורס מזכירות / ניסיון",
    skills: ["ארגון", "תקשורת", "ריבוי משימות"],
    work_environment: "משרד",
    social_interaction_level: "גבוה",
    disability_fit: ["לקות פיזית", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-009",
    name: "ספרנות",
    description: "סיוע לקוראים, ארגון ספרים וניהול מידע",
    salary_range: "6,500 - 11,000 ₪",
    education: "תעודת ספרנות",
    skills: ["סדר", "שירות", "ידע כללי"],
    work_environment: "ספרייה / מוסד",
    social_interaction_level: "בינוני",
    disability_fit: ["חרדה חברתית", "אוטיזם", "לקות ראייה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-010",
    name: "הזנת נתונים",
    description: "הזנת מידע למערכות מחשב בצורה מדויקת",
    salary_range: "6,000 - 10,000 ₪",
    education: "הכשרה בסיסית במחשבים",
    skills: ["דיוק", "סבלנות", "ריכוז"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-011",
    name: "הוראה",
    description: "לימוד תלמידים בכיתה או באופן פרטני",
    salary_range: "8,000 - 15,000 ₪",
    education: "תואר / הכשרת מורים",
    skills: ["סבלנות", "תקשורת", "הסברה"],
    work_environment: "בית ספר / מרכז למידה",
    social_interaction_level: "גבוה",
    disability_fit: ["לקות שמיעה", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-012",
    name: "ארכיון דיגיטלי",
    description: "סריקה, סיווג ושמירה של מסמכים דיגיטליים",
    salary_range: "7,000 - 12,000 ₪",
    education: "קורס ארכיונאות / מחשבים",
    skills: ["סדר", "דיוק", "ארגון"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות ראייה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-013",
    name: "עיצוב UX",
    description: "תכנון חוויית משתמש לאפליקציות ואתרים",
    salary_range: "12,000 - 25,000 ₪",
    education: "קורס UX / תואר רלוונטי",
    skills: ["אמפתיה", "יצירתיות", "חשיבה אנליטית"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "אוטיזם", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-014",
    name: "כתיבת תוכן",
    description: "כתיבת מאמרים, תוכן שיווקי ופוסטים לרשתות",
    salary_range: "6,000 - 14,000 ₪",
    education: "קורס כתיבה / ניסיון",
    skills: ["כתיבה", "יצירתיות", "מחקר"],
    work_environment: "מהבית / פרילנס",
    social_interaction_level: "נמוך",
    disability_fit: ["ADHD", "חרדה חברתית", "אוטיזם"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-015",
    name: "נגרות",
    description: "בניית רהיטים ופריטי עץ בהתאמה אישית",
    salary_range: "8,000 - 16,000 ₪",
    education: "קורס נגרות מקצועי",
    skills: ["מיומנות ידנית", "דיוק", "סבלנות"],
    work_environment: "סדנה / שטח",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "לקות למידה", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-016",
    name: "ניתוח נתונים",
    description: "איסוף, עיבוד וניתוח נתונים להפקת תובנות עסקיות",
    salary_range: "13,000 - 28,000 ₪",
    education: "קורס Data Analyst / תואר רלוונטי",
    skills: ["חשיבה אנליטית", "Excel / SQL", "דיוק", "סטטיסטיקה"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-017",
    name: "שיווק דיגיטלי",
    description: "ניהול קמפיינים, רשתות חברתיות וקידום אתרים",
    salary_range: "9,000 - 22,000 ₪",
    education: "קורס שיווק דיגיטלי",
    skills: ["יצירתיות", "ניתוח", "תקשורת", "כתיבה"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "גבוה",
    disability_fit: ["ADHD", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-018",
    name: "אבטחת מידע (סייבר)",
    description: "הגנה על מערכות ומידע מפני מתקפות והתקפות סייבר",
    salary_range: "16,000 - 38,000 ₪",
    education: "קורס סייבר / הסמכות מקצועיות",
    skills: ["חשיבה לוגית", "ריכוז", "פתרון בעיות", "למידה עצמאית"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-019",
    name: "איור דיגיטלי",
    description: "יצירת איורים ודמויות למשחקים, ספרים ותוכן שיווקי",
    salary_range: "7,000 - 17,000 ₪",
    education: "לימודי איור / לימוד עצמי",
    skills: ["יצירתיות", "תוכנות גרפיקה", "סבלנות"],
    work_environment: "מהבית / פרילנס",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-020",
    name: "ייעוץ מס",
    description: "ליווי עסקים ויחידים בענייני מיסוי ודיווחים לרשויות",
    salary_range: "11,000 - 26,000 ₪",
    education: "לימודי ייעוץ מס + הסמכה",
    skills: ["דיוק", "מספרים", "סדר", "אחריות"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "לקות פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-021",
    name: "סייעת חינוכית",
    description: "סיוע ותמיכה לתלמידים בכיתה ובמסגרות חינוכיות",
    salary_range: "6,000 - 10,000 ₪",
    education: "קורס סייעות / הכשרה",
    skills: ["סבלנות", "אמפתיה", "תקשורת"],
    work_environment: "בית ספר / גן",
    social_interaction_level: "גבוה",
    disability_fit: ["לקות שמיעה", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-022",
    name: "הדרכת קבוצות",
    description: "הנחיה והעברת סדנאות וקבוצות בנושאים מגוונים",
    salary_range: "7,000 - 14,000 ₪",
    education: "קורס הנחיה / הדרכה",
    skills: ["תקשורת", "הסברה", "אמפתיה"],
    work_environment: "מרכז קהילתי / מוסד",
    social_interaction_level: "גבוה",
    disability_fit: ["לקות שמיעה", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-023",
    name: "תכשיטנות",
    description: "עיצוב וייצור תכשיטים בעבודת יד ובהתאמה אישית",
    salary_range: "6,000 - 14,000 ₪",
    education: "קורס תכשיטנות מקצועי",
    skills: ["מיומנות ידנית", "יצירתיות", "דיוק", "סבלנות"],
    work_environment: "סדנה / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-024",
    name: "שרטוט אדריכלי",
    description: "הכנת שרטוטים טכניים ותכניות בנייה במערכות CAD",
    salary_range: "9,000 - 19,000 ₪",
    education: "קורס שרטוט / הנדסאי",
    skills: ["דיוק", "תוכנות CAD", "ריכוז", "חשיבה מרחבית"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-025",
    name: "פיתוח אפליקציות מובייל",
    description: "בניית אפליקציות לאנדרואיד ו-iOS מקצה לקצה",
    salary_range: "16,000 - 34,000 ₪",
    education: "קורס פיתוח מובייל / תואר",
    skills: ["חשיבה לוגית", "פתרון בעיות", "למידה עצמאית"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-026",
    name: "ניהול קהילה (Community)",
    description: "ניהול קהילות מקוונות, מענה למשתמשים ויצירת תוכן",
    salary_range: "8,000 - 16,000 ₪",
    education: "ניסיון / קורס שיווק",
    skills: ["תקשורת", "כתיבה", "ארגון", "אמפתיה"],
    work_environment: "מהבית / משרד",
    social_interaction_level: "גבוה",
    disability_fit: ["לקות פיזית", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-027",
    name: "בקרת איכות בייצור",
    description: "פיקוח על תהליכי ייצור ובדיקת תקינות מוצרים",
    salary_range: "8,000 - 15,000 ₪",
    education: "הכשרה מקצועית / קורס QA",
    skills: ["דיוק", "ריכוז", "סדר", "אחריות"],
    work_environment: "מפעל / מעבדה",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-028",
    name: "נציג/ת מכירות",
    description: "יצירת קשר עם לקוחות, הצגת מוצרים וסגירת עסקאות",
    salary_range: "8,000 - 18,000 ₪ + בונוסים",
    education: "הכשרת מכירות / ניסיון",
    skills: ["תקשורת", "משא ומתן", "סבלנות", "מטרה"],
    work_environment: "משרד / שטח / מהבית",
    social_interaction_level: "גבוה",
    disability_fit: ["ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-029",
    name: "אח/אחות",
    description: "טיפול סיעודי במוסדות רפואיים וקהילתיים",
    salary_range: "9,000 - 16,000 ₪",
    education: "לימודי סיעוד / רישוי",
    skills: ["אמפתיה", "סבלנות", "דיוק", "עמידה בלחץ"],
    work_environment: "בית חולים / קlinic",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-030",
    name: "פיזיותרפיסט/ית",
    description: "שיקום תנועה וטיפול פיזי בפציעות ומוגבלויות",
    salary_range: "10,000 - 18,000 ₪",
    education: "תואר / הסמכה בפיזיותרפיה",
    skills: ["ידע רפואי", "סבלנות", "תקשורת", "דיוק"],
    work_environment: "קlinic / בית חולים",
    social_interaction_level: "בינוני",
    disability_fit: ["חרדה חברתית", "פיזית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-031",
    name: "עוזר/ת משפטי",
    description: "סיוע לעורכי דין — מסמכים, מחקר ותיאום",
    salary_range: "8,000 - 14,000 ₪",
    education: "קורס paralegal / תעודה",
    skills: ["כתיבה", "ארגון", "ריכוז", "דיוק"],
    work_environment: "משרד עורכי דין",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-032",
    name: "מנהל/ת רכש ולוגיסטיקה",
    description: "ניהול ספקים, הזמנות ושרשרת אספקה",
    salary_range: "10,000 - 20,000 ₪",
    education: "תואר / קורס לוגיסטיקה",
    skills: ["משא ומתן", "ארגון", "Excel", "תקשורת"],
    work_environment: "משרד / מחסן",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "אוטיזם"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-033",
    name: "נציג/ת שירות לקוחות",
    description: "מענה לפניות לקוחות בטלפון, צ'at ומייל",
    salary_range: "7,000 - 12,000 ₪",
    education: "הכשרה / ללא",
    skills: ["סבלנות", "הקשבה", "פתרון בעיות", "כתיבה"],
    work_environment: "מוקד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["לקות שמיעה", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-034",
    name: "מגייס/ת HR",
    description: "גיוס עובדים, סינון קו\"ח וראיונות ראשוניים",
    salary_range: "9,000 - 18,000 ₪",
    education: "תואר / קורס HR",
    skills: ["תקשורת", "שיפוט", "ארגון", "כתיבה"],
    work_environment: "משרד / היברידי",
    social_interaction_level: "גבוה",
    disability_fit: ["ADHD"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-035",
    name: "הנדסאי/ת חשמל",
    description: "תכנון, שרטוט ופיקוח על מערכות חשמל",
    salary_range: "11,000 - 22,000 ₪",
    education: "הנדסאי חשמל",
    skills: ["חשיבה טכנית", "CAD", "דיוק", "בטיחות"],
    work_environment: "משרד / שטח",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "לקות שמיעה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-036",
    name: "הנדסאי/ת מכונות",
    description: "תכנון מכני, שרטוטים וליווי ייצור",
    salary_range: "11,000 - 21,000 ₪",
    education: "הנדסאי מכונות",
    skills: ["CAD", "חשיבה מרחבית", "דיוק", "פתרון בעיות"],
    work_environment: "משרד / מפעל",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-037",
    name: "פקיד/ת קבלה במלון",
    description: "קליטת אורחים, הזמנות ושירות בדesk קבלה",
    salary_range: "7,000 - 11,000 ₪",
    education: "קורס מלונאות",
    skills: ["שירות", "ארגון", "שפות", "מחשב"],
    work_environment: "מלון",
    social_interaction_level: "גבוה",
    disability_fit: ["חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-038",
    name: "טבח/ית",
    description: "הכנת מנות במסעדות, מטבחים וקייטring",
    salary_range: "8,000 - 16,000 ₪",
    education: "קורס בישול / ניסיון",
    skills: ["יצירתיות", "סבלנות", "עמידה בלחץ", "סדר"],
    work_environment: "מסעדה / מטבח",
    social_interaction_level: "בינוני",
    disability_fit: ["ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-039",
    name: "בקר/ת פנים",
    description: "בדיקת דוחות כספיים ותהליכים ארגוניים",
    salary_range: "12,000 - 25,000 ₪",
    education: "תואר / רואה חשבון / ביקורת",
    skills: ["דיוק", "ניתוח", "Excel", "ריכוז"],
    work_environment: "משרד",
    social_interaction_level: "נמוך",
    disability_fit: ["אוטיזם", "ADHD", "לקות למידה"],
    video_url: null,
    active: true,
  },
  {
    id: "prof-040",
    name: "מנהל/ת מוצר (Product)",
    description: "הגדרת דרישות מוצר, תעדוף ותיאום בין צוותים",
    salary_range: "18,000 - 35,000 ₪",
    education: "ניסיון בהייטק / קורס product",
    skills: ["חשיבה מערכתית", "תקשורת", "ניתוח", "כתיבה"],
    work_environment: "משרד / מהבית",
    social_interaction_level: "בינוני",
    disability_fit: ["אוטיזם", "ADHD", "חרדה חברתית"],
    video_url: null,
    active: true,
  },
].map((p) => ({
  ...p,
  category: PROFESSION_CATEGORY_BY_ID[p.id] ?? "other",
}));
